In [3]:
import numpy as np


In [2]:
print("hello")

hello


In [4]:
myarr=np.array([[1,23,34]])

In [5]:
myarr[0,1]

23

In [6]:
myarr.shape

(1, 3)

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[0,1]

23

In [9]:
myarr[0,1]=45

In [10]:
myarr

array([[ 1, 45, 34]])

#**array creation**#

In [11]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [17]:
np.array({12,23,23})

array({12, 23}, dtype=object)

In [18]:
zeros=np.zeros((2,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.shape

(2, 5)

In [21]:
rng=np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lnspace=np.linspace(1,5,12)

In [24]:
lnspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
lnspace1=np.linspace(1,4,4)

In [26]:
lnspace1

array([1., 2., 3., 4.])

In [27]:
emp=np.empty((4,6))

In [28]:
emp

array([[3.49999991e-296, 0.00000000e+000, 2.12393135e-314,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [1.60065647e-299, 1.57180701e-316, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [31]:
emp_like=np.empty_like(lnspace1)

In [32]:
emp_like

array([3.49999991e-296, 2.12393135e-314, 1.60065647e-299, 1.57180701e-316])

In [35]:
ide=np.identity(5)

In [36]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
ide.shape

(5, 5)

In [38]:
arr=np.arange(30)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
arr=arr.reshape(3,10)

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**NUMPY AXIS**

In [53]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [54]:
ar=np.array(x)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.sum(axis=0)

array([12,  8,  9])

In [57]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [58]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [59]:
ar.flat

In [60]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [61]:
ar.ndim

2

In [62]:
ar.size

9

In [63]:
ar.nbytes

36

In [64]:
one=np.array([1,2,3445,6])

In [65]:
one

array([   1,    2, 3445,    6])

In [66]:
one.argmax()

2

In [67]:
one.argmin()

0

In [68]:
one.argsort()

array([0, 1, 3, 2], dtype=int32)

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
ar.argmin()

8

In [71]:
ar.argmax()

6

In [72]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [73]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [74]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [75]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [76]:
ar2=np.array([[1, 5, 3],
       [4, 3, 6],
       [7, 7, 0]])

In [77]:
ar2

array([[1, 5, 3],
       [4, 3, 6],
       [7, 7, 0]])

In [78]:
ar+ar2

array([[ 2,  7,  6],
       [ 8,  8, 12],
       [14,  8,  0]])

In [79]:
ar*ar2

array([[ 1, 10,  9],
       [16, 15, 36],
       [49,  7,  0]])

In [80]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [82]:
ar2.sum()

36

In [83]:
ar2.max()

7

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [85]:
np.where(ar>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [86]:
type(np.where(ar>5))

tuple

In [87]:
np.count_nonzero(ar)

8

In [88]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

In [89]:
ar[1,2]=0

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int32))

**how to check space of numpy**

In [91]:
import sys

In [92]:
py_ar=[0,4,55,6]

In [93]:
np_ar=np.array(py_ar)

In [94]:
sys.getsizeof(1)*len(py_ar)

64

In [95]:
np_ar.itemsize*np_ar.size

16

In [96]:
np_ar.tolist()

[0, 4, 55, 6]